<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="equipos.css"?>
<!DOCTYPE equipos [
    <!ELEMENT  equipo (nombre, liga, ciudad, estadio, presidente, entrenador, patrocinador+, capitan)>
        <!ATTLIST equipo codequipo ID #REQUIRED>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT liga (#PCDATA)>
    <!ELEMENT estadio (#PCDATA)>
    <!ELEMENT presidente (#PCDATA)>
    <!ELEMENT entrenador (#PCDATA)>
    <!ELEMENT patrocinador (#PCDATA)>
    <!ELEMENT capitan (#PCDATA)>
    
    
    ]>

    <equipos>
        <equipo codequipo="e1">
            <nombre> FC BARCELONA </nombre>
            <liga> Liga Santander </liga>
            <ciudad> Barcelona </ciudad>
            <estadio> Camp Nou </estadio>
            <presidente> Joan Laporta </presidente>
            <entrenador> Xavi Hernandez </entrenador>
            <patrocinador> Rakuten </patrocinador>
            <patrocinador> Nike </patrocinador>
            <patrocinador> Beko </patrocinador>
            <capitan> Sergio Busquets </capitan>
        </equipo>
        <equipo codequipo="e2">
            <nombre> REAL MADRID </nombre>
            <liga> Liga Santander </liga>
            <ciudad> Madrid </ciudad>
            <estadio> Santiago Bernabeu </estadio>
            <presidente> Florentino Perez </presidente>
            <entrenador> Carlo Ancelotti </entrenador>
            <patrocinador> Adidas </patrocinador>
            <patrocinador> Fly Emirates </patrocinador>
            <capitan> Marcelo </capitan>
        </equipo>
        <equipo codequipo="e3">
            <nombre> FC BARCELONA </nombre>
            <liga> Liga Santander </liga>
            <ciudad> Barcelona </ciudad>
            <estadio> Camp Nou </estadio>
            <presidente> Joan Laporta </presidente>
            <entrenador> Xavi Hernandez </entrenador>
            <patrocinador> Rakuten </patrocinador>
            <patrocinador> Nike </patrocinador>
            <patrocinador> Beko </patrocinador>
            <capitan> Sergio Busquets </capitan>
        </equipo>
        <equipo codcodequipo="e4">
            <nombre> REAL MADRID </nombre>
            <liga> Liga Santander </liga>
            <ciudad> Madrid </ciudad>
            <estadio> Santiago Bernabeu </estadio>
            <presidente> Florentino Perez </presidente>
            <entrenador> Carlo Ancelotti </entrenador>
            <patrocinador> Adidas </patrocinador>
            <patrocinador> Fly Emirates </patrocinador>
            <capitan> Marcelo </capitan>
        </equipo>
        <equipo codequipo="e5">
            <nombre> FC BARCELONA </nombre>
            <liga> Liga Santander </liga>
            <ciudad> Barcelona </ciudad>
            <estadio> Camp Nou </estadio>
            <presidente> Joan Laporta </presidente>
            <entrenador> Xavi Hernandez </entrenador>
            <patrocinador> Rakuten </patrocinador>
            <patrocinador> Nike </patrocinador>
            <patrocinador> Beko </patrocinador>
            <capitan> Sergio Busquets </capitan>
        </equipo>
        <equipo codequipo="e6">
            <nombre> REAL MADRID </nombre>
            <liga> Liga Santander </liga>
            <ciudad> Madrid </ciudad>
            <estadio> Santiago Bernabeu </estadio>
            <presidente> Florentino Perez </presidente>
            <entrenador> Carlo Ancelotti </entrenador>
            <patrocinador> Adidas </patrocinador>
            <patrocinador> Fly Emirates </patrocinador>
            <capitan> Marcelo </capitan>
        </equipo>
        <equipo codequipo="e7">
            <nombre> FC BARCELONA </nombre>
            <liga> Liga Santander </liga>
            <ciudad> Barcelona </ciudad>
            <estadio> Camp Nou </estadio>
            <presidente> Joan Laporta </presidente>
            <entrenador> Xavi Hernandez </entrenador>
            <patrocinador> Rakuten </patrocinador>
            <patrocinador> Nike </patrocinador>
            <patrocinador> Beko </patrocinador>
            <capitan> Sergio Busquets </capitan>
        </equipo>
        <equipo codequipo="e8">
            <nombre> REAL MADRID </nombre>
            <liga> Liga Santander </liga>
            <ciudad> Madrid </ciudad>
            <estadio> Santiago Bernabeu </estadio>
            <presidente> Florentino Perez </presidente>
            <entrenador> Carlo Ancelotti </entrenador>
            <patrocinador> Adidas </patrocinador>
            <patrocinador> Fly Emirates </patrocinador>
            <capitan> Marcelo </capitan>
        </equipo>
        <equipo codequipo="e9">
            <nombre> FC BARCELONA </nombre>
            <liga> Liga Santander </liga>
            <ciudad> Barcelona </ciudad>
            <estadio> Camp Nou </estadio>
            <presidente> Joan Laporta </presidente>
            <entrenador> Xavi Hernandez </entrenador>
            <patrocinador >Rakuten </patrocinador>
            <patrocinador> Nike </patrocinador>
            <patrocinador> Beko </patrocinador>
            <capitan> Sergio Busquets </capitan>
        </equipo>
        <equipo codequipo="e10">
            <nombre> REAL MADRID </nombre>
            <liga> Liga Santander </liga>
            <ciudad> Madrid </ciudad>
            <estadio> Santiago Bernabeu </estadio>
            <presidente> Florentino Perez </presidente>
            <entrenador> Carlo Ancelotti </entrenador>
            <patrocinador> Adidas </patrocinador>
            <patrocinador> Fly Emirates </patrocinador>
            <capitan> Marcelo </capitan>
        </equipo>
        </equipos>
        

